### ISSUE TITLE
弱弱的问一下

### ISSUE THREAD

**Issue by ylwzbk** [zhuige-com/jiangqie_theme#1]
### 啥时候支持PHP8.0......呀

**Comment by longwenjunjie** [comment]
已有计划，敬请期待

**Comment by zhangmeng198** [comment]
正在安装您上传的主题：jiangqie_theme-main.zip
正在解压缩安装包…
正在安装主题…
无法安装这个包。 主题缺少style.css样式表。

**Comment by longwenjunjie** [comment]
😓，jqfree这个文件夹才是主题
