### ISSUE TITLE
首页最新文章右侧分类选项卡切换之后，再切回全部，显示有问题

### ISSUE THREAD

**Issue by miaoyanginfo** [zhuige-com/jiangqie_theme#4]
首页最新文章右侧分类选项卡切换之后，再切回全部，显示有问题。
切换到其他分类选项卡之后，再切回全部，会显示全部右侧的这个分类内容，而不是全部的内容。

**Comment by longwenjunjie** [comment]
多谢反馈！
此 bug 已修复
